server:
  port: ${PORT:8080}

logging:
  level:
    org.atmosphere: WARN

spring:
  mustache:
    check-template-location: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mcadmin

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

vaadin:
  productionMode: true
  theme:
    name: mytheme

email:
  sender: "${EMAIL_SENDER:joleksiysurovtsev@gmail.com}"
  recipient: "${EMAIL_RECIPIENT:o.surovtsev@spd-ukraine.com}"
  api-key: "${SENDGRID_API_KEY:}"